# Generated by Django 3.1.7 on 2023-05-13 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230420_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
